name: radev
channels:
  - conda-forge
dependencies:
  - basemap
  - make
  - git
  - matplotlib
  - jupyter
  - scipy
  - sphinx
  - sphinxcontrib-bibtex
  - nbsphinx
  - pandoc
  - recommonmark
  - sphinx
  - clang_osx-64
  - gfortran_osx-64
  - mkl
  - fftw
  - mpich
