name: linux

on: [push, pull_request]

jobs:
  test:
    name: test-build
    runs-on: [ubuntu-latest]
    # Needs to be here to properly detect changes to conda
    # see https://github.com/conda-incubator/setup-miniconda#IMPORTANT
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: radev
        environment-file: environment.yml
    - name: Build documentation
      continue-on-error: true
      run: |
        cd "$GITHUB_WORKSPACE"
        make doc
    - name: Build Rayleigh
      run: |
        cd "$GITHUB_WORKSPACE"
        echo $CONDA_PREFIX
        export MKLROOT=$CONDA_PREFIX
        ./configure -conda-mkl --FC=mpifort
        make -j
        make install