name: linux

on: [push, pull_request]

jobs:
  test:
    name: test-build
    runs-on: [ubuntu-18.04]
    container: geodynamics/rayleigh-buildenv-bionic

    steps:
      # Install git for the checkout action
    - name: install git
      run: apt install git
    - uses: actions/checkout@v2
    - name: setup
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "I am alive"
        ls .
        pwd
    - name: build documentation
      # First make sure notebooks do not contain output, then build doc
      run: |
        cd "$GITHUB_WORKSPACE"
        make clear_ipynb && git diff --exit-code --name-only
        make doc
