name: linux

on: [push, pull_request]

jobs:
  test:
    name: test-build
    runs-on: [ubuntu-latest]
    container: gassmoeller/rayleigh-buildenv-bionic

    steps:
  # We would like to use v2, but v2 requires a higher git version
  # than available in the container to clone a repo. In the current
  # container v2 strips the .git folder.
    - uses: actions/checkout@v1
    - name: Setup container
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "I am alive"
        ls .
        pwd
    - name: Build documentation
      # First make sure notebooks do not contain output, then build doc
      run: |
        cd "$GITHUB_WORKSPACE"
        make clear_ipynb && git diff --exit-code --name-only
        make doc
