name: linux

on: [push, pull_request]

jobs:
  test:
    name: test-build
    runs-on: [ubuntu-latest]
    container: gassmoeller/rayleigh-buildenv-focal

    steps:
    - uses: actions/checkout@v2
    - name: Setup container
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "I am alive"
        ls .
        pwd
    - name: Build documentation
      # First make sure notebooks do not contain output, then build doc
      run: |
        cd "$GITHUB_WORKSPACE"
#        make clear_ipynb && git diff --exit-code --name-only
#        make doc
    - name: Build Rayleigh
      # First make sure notebooks do not contain output, then build doc
      run: |
        ./configure --with-blas='/usr' --with-fftw='/usr' --with-lapack='/usr'
        make fdeps && git diff --exit-code
        make -j
        make install
    - name: Test
      run: |
        export OMPI_ALLOW_RUN_AS_ROOT=1
        export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
        cd "$GITHUB_WORKSPACE"
        cd tests/c2001_case0
        # This export avoids a warning about
        # a discovered, but unconnected infiniband network.
        mpirun -np 4 --oversubscribe ../../bin/rayleigh.dbg

        cd ..
        git diff > changes.diff
        git diff --exit-code --name-only

        cd "$GITHUB_WORKSPACE"
        ./tests/generic_input/run_test.sh
