name: linux

on: [push, pull_request]

jobs:
  test:
    name: test-build
    runs-on: [ubuntu-latest]
    container: geodynamics/rayleigh-buildenv-bionic

    steps:
      # Install git for the checkout action
    - name: Install git
      run: |
        apt update
        apt install -y git
    - uses: actions/checkout@v1
    - name: Setup container
      run: |
        cd "$GITHUB_WORKSPACE"
        echo "I am alive"
        ls .
        pwd
    - name: Build documentation
      # First make sure notebooks do not contain output, then build doc
      run: |
        cd "$GITHUB_WORKSPACE"
        make clear_ipynb && git diff --exit-code --name-only
        make doc
